### ISSUE TITLE
ベンチマーカの対応プロトコル確認(http2含む)

### ISSUE THREAD

**Issue by Goryudyuma** [kstm-su/kstm-isucon7q#44]

**Comment by bgpat** [comment]
ふぉのさんがやってた
cache-controlとか見逃してたのでなんとかしたい

**Comment by fono09** [comment]
手前にLBがいるかいないかわからんな、ってなってexpiresでいいだろという結論に至っていた。
予選での複数台を想定していなかったので試しても良かったかも。
